name: Bump Version and Create Release Automatically

on:
  push:
    branches:
      - main

jobs:
  bump_version:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: 'cat package.json'
        run: cat ./package.json

      - name: Automated Version Bump
        uses: phips28/gh-action-bump-version@v11.0.7
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag-prefix: 'v'

      - name: Get new version
        id: new_version
        run: echo "::set-output name=VERSION::$(node -p -e "require('./package.json').version")"

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: 'v${{ steps.new_version.outputs.VERSION }}'
          name: 'Release v${{ steps.new_version.outputs.VERSION }}'
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Merge main -> dev
        uses: devmasx/merge-branch@master
        with:
          type: now
          from_branch: main
          target_branch: dev
          message: Sync main to dev
          github_token: ${{ secrets.GITHUB_TOKEN }}
